package md.secumihai;

import javax.persistence.*;
import java.sql.Clob;
import java.util.Date;

/* This is a entity class where will be mapped and keeped all the changes in LEGE Nr. 172 din 25-07-2014
privind aprobarea Nomenclaturii combinate a mărfurilor*/
@Entity
@Table(name = "Law")
public class Law {

    //the id of the law will be generated by default
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private long id;

    // here will be keep
    @Column(name = "description")
    private String description;

    @Column(name = "initial_date")
    private Date intialDate;

    @Column(name = "final_date")
    private Date finalDate;

    @Lob
    @Column(name = "content")
    private Clob content;

    public Law() {

    }

    public Law(String description, Date intialDate, Date finalDate, Clob content) {
        this.description = description;
        this.intialDate = intialDate;
        this.finalDate = finalDate;
        this.content = content;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getIntialDate() {
        return intialDate;
    }

    public void setIntialDate(Date intialDate) {
        this.intialDate = intialDate;
    }

    public Date getFinalDate() {
        return finalDate;
    }

    public void setFinalDate(Date finalDate) {
        this.finalDate = finalDate;
    }

    public Clob getContent() {
        return content;
    }

    public void setContent(Clob content) {
        this.content = content;
    }
}